Fix issue with testGetKubeClientFallbackThrowsWhenNull (#271)
## Description

This PR fixes a problem with testGetKubeClientFallbackThrowsWhenNull
test case, i.e.,
```java
[ERROR] io.skodjob.testframe.MetricsCollectorTest.testGetKubeClientFallbackThrowsWhenNull -- Time elapsed: 1.735 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected io.fabric8.kubernetes.client.KubernetesClientException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
        at io.skodjob.testframe.MetricsCollectorTest.testGetKubeClientFallbackThrowsWhenNull(MetricsCollectorTest.java:131)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
Now it should work.

## Type of Change

* Bug fix (non-breaking change which fixes an issue)
* Update (Update version or update existing automation)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my
feature works
- [x] New and existing unit/integration tests pass locally with my
changes

---------

Signed-off-by: see-quick <maros.orsak159@gmail.com>